# Generated by Django 3.1.5 on 2021-01-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_booland'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booland',
        ),
    ]
