# Generated by Django 3.1.5 on 2021-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_delete_booland'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
