# Generated by Django 3.1.5 on 2021-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bool',
            field=models.BooleanField(default=False, verbose_name='Сохранить в черновик'),
        ),
    ]
