# Generated by Django 3.1.5 on 2021-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210109_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='изображения'),
            preserve_default=False,
        ),
    ]
