# Generated by Django 3.1.5 on 2021-01-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post-photo/', verbose_name='изображения'),
        ),
    ]
